# Generated by Django 4.1.7 on 2023-03-16 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admdatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
