# Generated by Django 4.1.7 on 2023-03-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_admdatetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pass_date',
            new_name='passdate',
        ),
    ]
